### PR TITLE
fix(psi): version 4 support

### PR DESCRIPTION
**Pull request by Kristinita**
### 1. Note

If you approve my changes, please don’t forget to publish the version with them to npm [**how was it here**](https://github.com/jrcryer/grunt-pagespeed/pull/30).

### 2. Summary

I updated:

1. grunt-pagespeed dependencies and devDependencies for compatibility with [**PSI 4**](https://github.com/GoogleChromeLabs/psi/releases/tag/v4.0.0)
1. Also, I updated `.travis.yml`

#### 3.1. Data

+ `Gruntfile.coffee`:

  ```coffee
  module.exports = (grunt) ->

    grunt.loadNpmTasks 'grunt-pagespeed'

    grunt.initConfig

      pagespeed:
        options:
          nokey: true
          url: "https://kristinita.netlify.app/"


        prod:
          options:
            paths: ["Programs/KristinitaLuckyLink"]
            locale: "en_US"
            strategy: "desktop"

    return

  ```

##### 3.2.1. Before

```text
npm install
grunt pagespeed --verbose
```

##### 3.2.2. After

Additionally, I installed updated grunt-pagespeed dependencies and devDependencies via [**npm-check**](https://www.npmjs.com/package/npm-check).

#### 4.1. Before

```js
Running "pagespeed:prod" (pagespeed) task
Verifying property pagespeed.prod exists in config…OK
File: [no files]
Options: options={"paths":["Programs/KristinitaLuckyLink"],"locale":"en_US","strategy":"desktop"}, nokey, url="https://kristinita.netlify.app/", paths=["Programs/KristinitaLuckyLink"], locale="en_US", strategy="desktop"
Warning: Expected a string Use --force to continue.

Aborted due to warnings.
```

#### 4.2. After

```js
Running "pagespeed:prod" (pagespeed) task
Verifying property pagespeed.prod exists in config…OK
File: [no files]
Options: options={"paths":["Programs/KristinitaLuckyLink"],"locale":"en_US","strategy":"desktop"}, nokey, url="https://kristinita.netlify.app/", paths=["Programs/KristinitaLuckyLink"], locale="en_US", strategy="desktop"

--------------------------------------------------------

Summary

URL:          kristinita.netlify.app/programs/kristinitaluckylink
Strategy:     desktop
Performance:  87

Field Data

The Chrome User Experience Report does not have sufficient real-world speed data for this page.


Lab Data

Cumulative Layout Shift                    | 0.491
First Contentful Paint                     | 0.8s
Largest Contentful Paint                   | 1.8s
Speed Index                                | 0.8s
Time to Interactive                        | 1.7s
Total Blocking Time                        | 20ms

Opportunities

Avoid multiple page redirects              | 230ms
Minify CSS                                 | 40ms

--------------------------------------------------------


Done.
```

#### 4.3. PSI CLI

```js
D:\SashaDemoRepositories\SashaGruntDebugging>psi https://kristinita.netlify.app/Programs/KristinitaLuckyLink --strategy=desktop

--------------------------------------------------------

Summary

URL:          kristinita.netlify.app/programs/kristinitaluckylink
Strategy:     desktop
Performance:  88

Field Data

The Chrome User Experience Report does not have sufficient real-world speed data for this page.


Lab Data

Cumulative Layout Shift                    | 0.389
First Contentful Paint                     | 0.9s
Largest Contentful Paint                   | 1.7s
Speed Index                                | 0.9s
Time to Interactive                        | 1.7s
Total Blocking Time                        | 10ms

Opportunities

Avoid multiple page redirects              | 230ms
Minify CSS                                 | 80ms

--------------------------------------------------------
```

### 5. Testing environment

1. Windows 10.0.18363 Pro N for Workstations 64-bit EN
1. Node.js 14.12.0
1. Grunt 1.3.0
1. grunt-cli 1.3.2
1. psi 4.0.1
1. grunt-pagespeed 2.0.1
1. npm-check 5.9.2

Thanks.

### CODE REVIEW

**Comment by Kristinita** [comment]
@jrcryer , ping. Please, review this pull request.

Thanks.

**Comment by jrcryer** [comment]
Thanks @Kristinita

**Comment by Kristinita** [comment]
@jrcryer, thanks!

Please, don’t forget grunt-pagespeed version with this changes to the npm.

**Comment by jrcryer** [comment]
Hi @Kristinita  - I've tested this before I bumped the version and published.  It looks to be failing currently and the travis CI build is also failing:

https://travis-ci.org/github/jrcryer/grunt-pagespeed

Can you resolve these please? I will publish once I know the package is working.

Thanks,

James

**Comment by Kristinita** [comment]
@jrcryer,

### 1. Travis build

> It looks to be failing currently and the travis CI build is also failing:
>
> https://travis-ci.org/github/jrcryer/grunt-pagespeed

Excuse me, Travis build of my fork [**was passed**](https://travis-ci.com/github/Kristinita/grunt-pagespeed/builds/186816825) and I didn’t see [**the error**](https://travis-ci.com/github/Kristinita/grunt-pagespeed/builds/186816825#L208-L210).

But this problem [**is solved by adding this line**](https://docs.travis-ci.com/user/build-stages/#build-stages-and-deployments) to your `.travis.yml`:

```yaml
script: skip
```

See how it works in the [**Travis build of my fork**](https://travis-ci.com/github/Kristinita/grunt-pagespeed/builds/195467758#L220).

Or better add some tests :smile: .

### 2. grunt-pagespeed

> I've tested this before I bumped the version and published. It looks to be failing currently

Can you add details what did you mean? grunt-pagespeed version after my pull-request already works for me as expected.

#### 2.1. MCVE

##### 2.1.1. Data

You can see it in the [**`KiraPageSpeed` branch**](https://github.com/Kristinita/SashaGruntDebugging/tree/KiraPageSpeed) of my demo/debugging repository.

+ The part of the `.travis.yml`:

```yaml
install:
- npm install -g grunt-cli
- npm install

script:
- grunt pagespeed --verbose
```

+ The part of the `package.json`:

```json
"devDependencies": {
  "coffeescript": "^2.5.1",
  "grunt": "^1.3.0",
  "grunt-pagespeed": "github:jrcryer/grunt-pagespeed"
}
```

`Gruntfile.coffee` as in the section 3.1 of my [**initial post**](https://github.com/jrcryer/grunt-pagespeed/pull/36).

##### 2.1.2. Behavior

See the [**Travis build**](https://travis-ci.com/github/Kristinita/SashaGruntDebugging/jobs/418195535) for this configuration:

```js
Running "pagespeed:prod" (pagespeed) task
Verifying property pagespeed.prod exists in config…OK
File: [no files]
Options: options={"paths":["Programs/KristinitaLuckyLink"],"locale":"en_US","strategy":"desktop"}, nokey, url="https://kristinita.netlify.app/", paths=["Programs/KristinitaLuckyLink"], locale="en_US", strategy="desktop"

--------------------------------------------------------

Summary
URL:          kristinita.netlify.app/programs/kristinitaluckylink
Strategy:     desktop
Performance:  88
Field Data
The Chrome User Experience Report does not have sufficient real-world speed data for this page.
Lab Data
Cumulative Layout Shift                    | 0.465
First Contentful Paint                     | 0.6s
Largest Contentful Paint                   | 1.8s
Speed Index                                | 0.9s
Time to Interactive                        | 1.0s
Total Blocking Time                        | 0ms
Opportunities
Avoid multiple page redirects              | 230ms
Initial server response time was short     | 153ms
Minify CSS                                 | 40ms

--------------------------------------------------------

Done.

The command "grunt pagespeed --verbose" exited with 0.
```

##### 2.1.3. Environment

1. Windows 10.0.19041.508 Pro N for Workstations 64-bit EN (local)
1. Ubuntu 20.04.1 LTS (Travis CI)

Thanks.

**Comment by Kristinita** [comment]
@jrcryer, on npm version of grunt-pagespeed [**that published 6 years ago**](https://www.npmjs.com/package/grunt-pagespeed). Please, update grunt-pagespeed on npm.

Thanks.

**Pull request merged**
